- hosts: '{{ nodes }}'
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Install apt-cacher-ng
    apt:
      name: apt-cacher-ng
      state: present
  - name: Start and enable apt-cacher-ng
    systemd:
      name: apt-cacher-ng
      state: started
      enabled: true
  - name: Uncomment to serve HTTPS repositories
    lineinfile:
      dest: /etc/apt-cacher-ng/acng.conf
      regexp: '^#\s*PassThroughPattern:\s*\.\*.*$'
      line: 'PassThroughPattern: .* # this would allow CONNECT to everything'
  - name: Restart apt-cacher-ng
    systemd:
      name: apt-cacher-ng
      state: restarted